data_ingestion:
  bucket_name: "house-prices-advanced-regression-techniques"
  storage_path: "s3.ir-tbz-sh1.arvanstorage.ir"

  object_name_train: "train.csv"
  object_name_test: "test.csv"

  artifact_dir: "artifacts"

  val_ratio: 0.1
  random_state: 42
  shuffle: true

  target_column: "SalePrice"
  dropna_target: true
